# ══════════════════════════════════════════════
#  Cortex 3.1.7 — Configuration
# ══════════════════════════════════════════════

play.http.secret.key = "changeme_cortex_secret_key_min32chars_ok"

search {
  uri = "http://elasticsearch-cortex:9200"
}

job {
  directory = "/tmp/cortex-jobs"
  runners = [process, docker]
}

process {
  pythonPath = "/usr/bin/python3"
}